type: app
description: Default stackfile usecase description
# template used to create the project
template: new-stackspot-migrator/<template-name>
inputs:
  some_input: value
# list of plugins to be applied after project creation
plugins:
  - plugin: new-stackspot-migrator/<plugin-name>
    inputs:
      some_input: value
      some_list:
        - item1
        - item2
