name: plugin-migrator
description: Reads a plugin folder and update files to the new stackspot format
supported-os:
  - windows
  - linux
  - mac
inputs:
  - label: "Plugin folder full path:"
    type: text
    name: plugin_folder_path
    required: true
command:
  linux: |
    python3 {{component_path}}/main.py "{{plugin_folder_path}}"
  mac: |
    python3 {{component_path}}/main.py "{{plugin_folder_path}}"
  windows: |
    cmd /C python3 {{component_path}}\main.py "{{plugin_folder_path}} "
