name: plugin-migrator
description: Reads a plugin or template folder and updates its files to the new stackspot format
supported-os:
  - windows
  - linux
  - mac
inputs:
  - label: "Plugin or Template folder full path:"
    type: text
    name: plugin_or_template_folder_path
    required: true
command:
  linux: |
    python3 {{component_path}}/main.py "{{plugin_or_template_folder_path}}"
  mac: |
    python3 {{component_path}}/main.py "{{plugin_or_template_folder_path}}"
  windows: |
    cmd /C python {{component_path}}\main.py "{{plugin_or_template_folder_path}} "
